### PR TITLE
Add community calendar

### LINKED ISSUE #15: Embedded community calendar is missing
Here:

https://melissawm.github.io/napari-theme-var/community/meeting_schedule.html

I think this is ok for a 0.1 release but I'd rest easier if you saw a way forward there... 😅

### PR DESCRIPTION
**Pull request by melissawm**
May close #15 

To try and make the stack as clean as possible while still keeping the community calendar nicely rendered in our pages, I've switched over from [react-calendar](https://www.npmjs.com/package/react-calendar) to [fullCalendar](https://fullcalendar.io/). This creates a different visual, but functionality is mostly there. fullCalendar is also being used by [Scientific Python](https://github.com/scientific-python/scientific-python.org/blob/3fa331007903b99098dd8b6c7063d9cab3c9b1f5/layouts/calendars/list.html#L40) and I think going with a solution that is already used by the community can be interesting 😄 

This PR is a work in progress, but I'd love to get some feedback on whether or not this is fine. 

Here's how the rendered page looks like: https://melissawm.github.io/napari-theme-var/community/meeting_schedule.html

cc @jni

### CODE REVIEW

**Comment by jni** [comment]
Yeah I really like it! I love that we get list view "for free", and you've gotten the look really close! So 👍 from me!

**Comment by jni** [comment]
(And +💯 to using what the rest of the community is using! ❤️‍🔥)

**Review by jni — APPROVED** [review]

**Comment by psobolewskiPhD** [comment]
Love it!
It fixes the Safari calendar issues!
This PR:
image
Live napari.org:
image

**Comment by psobolewskiPhD** [comment]
Also, it's clipped in the screenshot, but the navigation at the bottom is fixed!
https://github.com/napari/napari-sphinx-theme/issues/126

**Comment by melissawm** [comment]
Ok - missing is just the event popover: right now it looks very basic, but the information is there I will merge and the missing piece here is changes that should happen on the napari/docs side. I will submit those once we have figured out the deployment for the napari-sphinx-theme package and any pending fixes.

**Pull request merged**
